[package]
name = "rgaa-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
rgaa-core = { path = "../rgaa-core" }
rgaa-obscura = { path = "../rgaa-obscura" }
rgaa-rules = { path = "../rgaa-rules" }
thiserror = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { version = "1.0", features = ["full"] }
serde_yaml = "0.9"
uuid = { version = "1.0", features = ["v4"] }

[dev-dependencies]
indicatif = "0.17"