use std::path::Path;
use std::process::Command;

#[derive(Debug, Clone)]
pub enum ExportFormat {
    Json,
    Html,
    Pdf,
}

impl ExportFormat {
    pub fn from_extension(ext: &str) -> Option<Self> {
        match ext.to_lowercase().as_str() {
            "json" => Some(ExportFormat::Json),
            "html" | "htm" => Some(ExportFormat::Html),
            "pdf" => Some(ExportFormat::Pdf),
            _ => None,
        }
    }

    pub fn ext(&self) -> &'static str {
        match self {
            ExportFormat::Json => "json",
            ExportFormat::Html => "html",
            ExportFormat::Pdf => "pdf",
        }
    }
}

pub fn export_json(audit: &rgaa_core::AuditResult, path: &Path) -> std::io::Result<()> {
    let json = serde_json::to_string_pretty(audit).map_err(|e| {
        std::io::Error::new(std::io::ErrorKind::InvalidData, e.to_string())
    })?;
    std::fs::write(path, json)?;
    Ok(())
}

pub fn export_html(audit: &rgaa_core::AuditResult, path: &Path) -> std::io::Result<()> {
    let taux = audit.taux_global;
    let label = if taux >= 80.0 {
        "Conforme"
    } else if taux >= 50.0 {
        "Partiellement conforme"
    } else {
        "Non conforme"
    };
    let color = if taux >= 80.0 {
        "#22c55e"
    } else if taux >= 50.0 {
        "#eab308"
    } else {
        "#ef4444"
    };

    let mut rows = String::new();
    if let Some(page) = audit.pages.first() {
        for result in &page.criteria {
            let status_str = match result.status {
                rgaa_core::CriterionStatus::Pass => "PASS",
                rgaa_core::CriterionStatus::Fail => "FAIL",
                rgaa_core::CriterionStatus::NotTested => "N/A",
                rgaa_core::CriterionStatus::NeedsReview => "REVIEW",
                rgaa_core::CriterionStatus::NotApplicable => "N/A",
                rgaa_core::CriterionStatus::Error => "ERROR",
            };
            let row_color = match result.status {
                rgaa_core::CriterionStatus::Pass => "#22c55e",
                rgaa_core::CriterionStatus::Fail | rgaa_core::CriterionStatus::Error => "#ef4444",
                rgaa_core::CriterionStatus::NeedsReview => "#eab308",
                _ => "transparent",
            };
            rows.push_str(&format!(
                r#"<tr style="background:{row_color}20">
                    <td>{}</td><td>{}</td><td>{}</td>
                </tr>"#,
                result.criterion_id, status_str, result.title
            ));
        }
    }

    let html = format!(
        r#"<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>RGAA Audit — {}</title>
<style>
  body{{font-family:system-ui,sans-serif;margin:2rem;background:#0f172a;color:#e2e8f0}}
  h1{{color:#38bdf8}}
  .score{{font-size:3rem;font-weight:700;color:{color}}}
  table{{width:100%;border-collapse:collapse;margin-top:1rem}}
  th{{background:#1e293b;padding:.5rem;text-align:left}}
  td{{padding:.4rem;border-bottom:1px solid #334155}}
  tr:hover{{background:#1e293b}}
</style>
</head>
<body>
<h1>RGAA Audit Report</h1>
<p>URL: <strong>{}</strong></p>
<p>Score: <span class="score">{:.1}%</span> — {}</p>
<p>Passed: {} | Failed: {} | N/A: {}</p>
<table>
<thead><tr><th>ID</th><th>Status</th><th>Topic</th></tr></thead>
<tbody>{}</tbody>
</table>
<p style="margin-top:2rem;color:#64748b">Generated by rgaa-cli</p>
</body>
</html>"#,
        audit.url, audit.url, taux, label, audit.passed, audit.failed, audit.na, rows
    );

    std::fs::write(path, html)?;
    Ok(())
}

pub fn export_pdf(audit: &rgaa_core::AuditResult, path: &Path) -> Result<(), String> {
    let html_path = path.with_extension("html");
    export_html(audit, &html_path).map_err(|e| e.to_string())?;

    let wkhtmltopdf = std::env::var("RGAA_WKHTMLTOPDF")
        .unwrap_or_else(|_| "wkhtmltopdf".to_string());

    let output = Command::new(&wkhtmltopdf)
        .args(["--enable-local-file-access", html_path.to_str().unwrap(), path.to_str().unwrap()])
        .output()
        .map_err(|e| format!("failed to run {}: {e}", wkhtmltopdf))?;

    if !output.status.success() {
        return Err(format!(
            "wkhtmltopdf failed: {}",
            String::from_utf8_lossy(&output.stderr)
        ));
    }

    let _ = std::fs::remove_file(&html_path);
    Ok(())
}

pub fn export(audit: &rgaa_core::AuditResult, path: &Path) -> Result<ExportFormat, String> {
    let ext = path
        .extension()
        .and_then(|e| e.to_str())
        .unwrap_or("json");
    let format = ExportFormat::from_extension(ext)
        .ok_or_else(|| format!("unsupported export format: {ext}"))?;

    match &format {
        ExportFormat::Json => export_json(audit, path).map_err(|e| e.to_string())?,
        ExportFormat::Html => export_html(audit, path).map_err(|e| e.to_string())?,
        ExportFormat::Pdf => export_pdf(audit, path)?,
    }

    Ok(format)
}
